Azure-Samples/service-fabric-cluster-templates

5-VM-Windows-OMS-UnSecure/sfclusteroms.json

This template deploys the following along with a standard SF unsecure cluster
1) OMS Workspace configured to read from Service Fabric storage tables
2) Service Fabric OMS solution
3) OMS Agent configured to read 2 sample performance counters
@aljo-microsoft can you review?

OMS configured cluster

---

5-VM-Ubuntu-1-NodeTypes-Secure/new-service-fabric-cluster-certificate.sh

Provide a shell script to create an Azure Key Vault and related certificates for secure management of a Service Fabric cluster. The script provides similar functionality to the existing PowerShell script.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Shell script to create key vault and certificates.

---

Ubuntu-NodeType-Loop-Secure/AzureDeploy.Parameters.json
Ubuntu-NodeType-Loop-Secure/AzureDeploy.json
Ubuntu-NodeType-Loop-Secure/README.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

ARM template with resource loops

---

10-VM-Ubuntu-2-NodeType-Secure/AzureDeploy.Parameters.json
10-VM-Ubuntu-2-NodeType-Secure/AzureDeploy.json

Update 2 nodetype secure ubuntu cluster for Service Fabric template. 
* ...
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```

update 2 nodetype ubuntu secure cluster

---

10-VM-Windows-2-NodeType-Secure/AzureDeploy.Parameters.json
10-VM-Windows-2-NodeType-Secure/AzureDeploy.json
5-VM-Windows-OMS-UnSecure/sfclusteroms.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Add oms to templates

---

7-VM-Windows-3-NodeTypes-Secure-NSG/AzureDeploy.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Changing durability level of node types to silver

---

5-VM-Ubuntu-1-NodeType-Secure-OMS/5-VM-Ubuntu-1-NodeType-Secure-OMS.json
5-VM-Ubuntu-1-NodeType-Secure-OMS/5-VM-Ubuntu-1-NodeType-Secure-OMS.parameters.json

The current reference to the sample will be outdated. Moving the sample to this repo.

added linux secure oms sample

---

7-VM-Ubuntu-1804-3-NodeTypes-Secure/README.md

Updates an incorrect reference in an azure deploy link.

Updated deploy link ref

---

7-VM-Ubuntu-1804-3-NodeTypes-Secure/README.md

Updates README.md for Ubuntu 18.04 sample, removing screenshots from Azure Portal, as support for portal deployment is not yet finished.

updated readme

---

5-VM-Ubuntu-1804-1-NodeType-Secure/AzureDeploy.Parameters.json
5-VM-Ubuntu-1804-1-NodeType-Secure/AzureDeploy.json
5-VM-Ubuntu-1804-1-NodeType-Secure/New-ServiceFabricClusterCertificate.ps1
5-VM-Ubuntu-1804-1-NodeType-Secure/README.md
5-VM-Ubuntu-1804-1-NodeType-Secure/new-service-fabric-cluster-certificate.sh

Another new template supporting Ubuntu 1804 in service fabric ARM deployments, this time showing a 5 VM 1 node type scenario.
```
[ ] Bugfix
[X ] Feature
```

Added 5 node 1 nodetype ubuntu 1804 sample

---

Primary-NodeType-Scaling-Sample/AzureDeploy-1.json
Primary-NodeType-Scaling-Sample/AzureDeploy-2.json
Primary-NodeType-Scaling-Sample/AzureDeploy-3.json
Primary-NodeType-Scaling-Sample/AzureDeploy-4.json
Primary-NodeType-Scaling-Sample/AzureDeploy.Parameters.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Sample templates for scaling the primary node type

---

15-VM-Windows-Multiple-AZ-Secure/AzureDeploy.json

Removing param to be renamed.
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...

Removing param to be renamed

---

SF-Managed-Basic-SKU-1-NT/README.md
SF-Managed-Basic-SKU-1-NT/azuredeploy.json
SF-Managed-Basic-SKU-1-NT/azuredeploy.parameters.json
SF-Managed-Basic-SKU-1-NT/metadata.json
SF-Managed-Standard-SKU-1-NT/README.md
SF-Managed-Standard-SKU-1-NT/azuredeploy.json
SF-Managed-Standard-SKU-1-NT/azuredeploy.parameters.json
SF-Managed-Standard-SKU-1-NT/metadata.json
SF-Managed-Standard-SKU-2-NT/README.md
SF-Managed-Standard-SKU-2-NT/azuredeploy.json
SF-Managed-Standard-SKU-2-NT/azuredeploy.parameters.json
SF-Managed-Standard-SKU-2-NT/metadata.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Add samples of service fabric managed clusters

---

SF-Managed-Basic-SKU-1-NT/README.md
SF-Managed-Standard-SKU-1-NT/README.md
SF-Managed-Standard-SKU-2-NT/README.md

* Updates SF managed cluster template readmes with publish links
* Adds formatting for SKUs, VM sizes, etc
* Consistency for title "Service Fabric managed clusters"
```
[] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[] Code style update (formatting, local variables)
[X] Documentation content changes
```

Update SF managed cluster template readmes with publish links

---

15-VM-Windows-Multiple-AZ-Secure/AzureDeploy.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

New property model

---

15-VM-Windows-Multiple-AZ-Secure/AzureDeploy.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Removing test extn

---

SF-Managed-Standard-SKU-1-NT-MI/README.md
SF-Managed-Standard-SKU-1-NT-MI/azuredeploy.json
SF-Managed-Standard-SKU-1-NT-MI/metadata.json

* A new template making use of the feature to add managed identities to Service Fabric managed cluster node types
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
*  From the README.md, press the 'Deploy' button, or copy and paste the contents of azuredeploy.json into a new template deployment in the Azure portal.
* azuredeploy.json
* metadata.json
Corresponds to the following documentation PR: https://github.com/MicrosoftDocs/azure-docs-pr/pull/139031

Added 1-NT managed cluster with MI template

---

15-VM-Windows-Multiple-AZ-Secure/AzureDeploy.json

Updating template to not use LRS storage accounts for logs.
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[ ] Feature
[ X] Other... Please describe:
Updating template to not use LRS storage accounts for logs.
```
cd [repo-name]
npm install
```
```
```
* ...

Storage account type update

---

15-VM-Windows-Multiple-AZ-Secure/AzureDeploy.json

* ...
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[ ] Feature
[ X] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fixing recommendation

---

SF-Managed-Basic-SKU-1-NT/azuredeploy.json
SF-Managed-Standard-SKU-1-NT-MI/azuredeploy.json
SF-Managed-Standard-SKU-1-NT/azuredeploy.json
SF-Managed-Standard-SKU-2-NT/azuredeploy.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update ARM API version

---

SF-Managed-Standard-SKU-1-NT-DiskEncryption/README.md
SF-Managed-Standard-SKU-1-NT-DiskEncryption/azuredeploy.json
SF-Managed-Standard-SKU-1-NT-DiskEncryption/azuredeploy.parameters.json
SF-Managed-Standard-SKU-1-NT-DiskEncryption/metadata.json

* Adding sample for Service Fabric managed clusters (preview) disk encryption
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
Follow this tutorial: https://review.docs.microsoft.com/en-us/azure/service-fabric/how-to-enable-managed-cluster-disk-encryption?branch=pr-en-us-146620&tabs=azure-powershell
Publish link (live by 2/17/21 10am): https://docs.microsoft.com/en-us/azure/service-fabric/how-to-enable-managed-cluster-disk-encryption
Verify the cluster nodes have disk encryption enabled: https://review.docs.microsoft.com/en-us/azure/service-fabric/how-to-enable-m …

SF managed cluster disk encryption sample

---

10-VM-2-NodeTypes-Windows-Stateless-Secure/AzureDeploy.json
15-VM-2-NodeTypes-Windows-Stateless-CrossAZ-Secure/AzureDeploy.json

For automatic OS image upgrade the typeHandlerVersion 1.1 is mandatory.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix typehandlerversion

---

SF-Managed-Basic-SKU-1-NT/README.md
SF-Managed-Basic-SKU-1-NT/azuredeploy.json
SF-Managed-Basic-SKU-1-NT/azuredeploy.parameters.json
SF-Managed-Basic-SKU-1-NT/metadata.json
SF-Managed-Standard-SKU-1-NT-AppSecret/README.md
SF-Managed-Standard-SKU-1-NT-AppSecret/azuredeploy.json
SF-Managed-Standard-SKU-1-NT-AppSecret/azuredeploy.parameters.json
SF-Managed-Standard-SKU-1-NT-AppSecret/metadata.json
SF-Managed-Standard-SKU-1-NT-DiskEncryption/README.md
SF-Managed-Standard-SKU-1-NT-DiskEncryption/azuredeploy.json
SF-Managed-Standard-SKU-1-NT-DiskEncryption/azuredeploy.parameters.json
SF-Managed-Standard-SKU-1-NT-DiskEncryption/metadata.json
SF-Managed-Standard-SKU-1-NT-MI/README.md
SF-Managed-Standard-SKU-1-NT-MI/azuredeploy.json
SF-Managed-Standard-SKU-1-NT-MI/azuredeploy.parameters.json
SF-Managed-Standard-SKU-1-NT-MI/metadata.json
SF-Managed-Standard-SKU-1-NT/README.md
SF-Managed-Standard-SKU-1-NT/azuredeploy.json
SF-Managed-Standard-SKU-1-NT/azuredeploy.parameters.json
SF-Managed-Standard-SKU-1-NT/metadata.json
SF-Managed-Standard-SKU-2-NT-CrossAZ/README.md
SF-Managed-Standard-SKU-2-NT-CrossAZ/azuredeploy.json
SF-Managed-Standard-SKU-2-NT-CrossAZ/azuredeploy.parameters.json
SF-Managed-Standard-SKU-2-NT-CrossAZ/metadata.json
SF-Managed-Standard-SKU-2-NT/README.md
SF-Managed-Standard-SKU-2-NT/azuredeploy.json
SF-Managed-Standard-SKU-2-NT/azuredeploy.parameters.json
SF-Managed-Standard-SKU-2-NT/metadata.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Updated samples for GA release

---

SF-Managed-Standard-SKU-2-NT-CrossAZ/README.md
SF-Managed-Standard-SKU-2-NT-Stateless/README.md
SF-Managed-Standard-SKU-2-NT-Stateless/azuredeploy.json
SF-Managed-Standard-SKU-2-NT-Stateless/azuredeploy.parameters.json
SF-Managed-Standard-SKU-2-NT-Stateless/metadata.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Add stateless node type

---

SF-Managed-Standard-SKU-2-NT-HostEncryption/README.md
SF-Managed-Standard-SKU-2-NT-HostEncryption/azuredeploy.json
SF-Managed-Standard-SKU-2-NT-HostEncryption/azuredeploy.parameters.json
SF-Managed-Standard-SKU-2-NT-HostEncryption/metadata.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Sample for host encryption

---

5-VM-Windows-1-NodeTypes-Secure-NSG/azuredeploy.json
7-VM-Windows-3-NodeTypes-Secure-NSG/AzureDeploy.json

* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[x] Documentation content changes
[x] Other... Please describe: 
Overwriting the default rules is causing complications with the cluster setup. New rules are also aligned with the update for the doc https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-best-practices-networking
```
```
cd [repo-name]
npm install
```
```
```
* ...

Adding new set of NSG rules according to the 'network best practices' doc update

---

SF-Managed-Standard-SKU-1-NT-MI/README.md

Fixed a broken link to the docs. Previously pointed to a 404.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
N/A
N/A
N/A
Just updating a readme to fix a broken link

Fixed broken link to docs

---

15-VM-2-NodeTypes-Windows-Stateless-CrossAZ-Secure/AzureDeploy.json
15-VM-Windows-Cross-AZ-Secure-UD-Override/AzureDeploy.json
15-VM-Windows-Cross-AZ-Secure/AzureDeploy.json
15-VM-Windows-Multiple-AZ-Secure/AzureDeploy.json

* ...
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
``` Updating the new PublicIP API version and its corresponding zone config.
```
cd [repo-name]
npm install
```
```
```
* ...

Adding zoneConfig to PublicIP with new API which was a breaking change

---

SF-Managed-Standard-SKU-1-NT-MRP/README.md
SF-Managed-Standard-SKU-1-NT-MRP/azuredeploy.json
SF-Managed-Standard-SKU-1-NT-MRP/azuredeploy.parameters.json
SF-Managed-Standard-SKU-1-NT-MRP/metadata.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

templates for MRP

---

SF-Managed-Standard-SKU-1-NT-PIPrefix/README.md
SF-Managed-Standard-SKU-1-NT-PIPrefix/azuredeploy.json
SF-Managed-Standard-SKU-1-NT-PIPrefix/azuredeploy.parameters.json
SF-Managed-Standard-SKU-1-NT-PIPrefix/metadata.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Template for Public IP Prefix

---

SF-Managed-Standard-SKU-1-NT-DDoSNwProtection/README.md
SF-Managed-Standard-SKU-1-NT-DDoSNwProtection/azuredeploy.json
SF-Managed-Standard-SKU-1-NT-DDoSNwProtection/azuredeploy.parameters.json
SF-Managed-Standard-SKU-1-NT-DDoSNwProtection/metadata.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

template for ddos protection in managed cluster 

---

SF-Managed-Standard-SKU-1-NT-AppGateway/README.md
SF-Managed-Standard-SKU-1-NT-AppGateway/metadata.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

ARM template for Application Gateway

---

Windows-Cluster-Managed-Identity-Auth/deploySfrpMI.ps1
Windows-Cluster-Managed-Identity-Auth/parameters_WindowsMI.json
Windows-Cluster-Managed-Identity-Auth/template_WindowsMI.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

new sample cluster template for windows mi-auth

---

SF-Managed-Basic-SKU-1-NT/azuredeploy.parameters.json

change "deploymentTemplate" to "deploymentParameters" because it's a parameter file
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

update schema to deploymentParameters

---

15-VM-2-NodeTypes-Windows-Stateless-CrossAZ-Secure/AzureDeploy.Parameters.json
15-VM-2-NodeTypes-Windows-Stateless-CrossAZ-Secure/AzureDeploy.json

1. Fixed PublicIP resource SKU and allocation method
2. Fixed Loadbalalncer SKU
3. Fixed LoadBalancerBEAddressNatPool port range
4. Fixed missing comma issue in VMSS resource
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fixing issues with template deployment

---

SF-Managed-Standard-SKU-1-NT-AzureMonitor/azuredeploy.json
SF-Managed-Standard-SKU-2-NT-AzureMonitor/azuredeploy.json

fix azure monitor agent name for data collection  rules configuration failure
```
[ ] Yes
[x ] No
```
```
[x ] Bugfix
[ ] Feature
```
* deploy managed cluster with azure monitor agent
```
cd [repo-name]
new-azresourcegroupdeployment
```
```
* add data collection rule
```
Verify that the rule adds successfully without error
* ...

fix azure monitor agent name for data collection  rules configuration failure
